pub mod blockchain;
pub mod data_structures_1;
pub mod data_structures_2;
pub mod dynamic_programming;
pub mod graph_based_dsa_1;
pub mod greedy_algs;
pub mod other_algs;
pub mod sorting_and_searching_algs;
pub mod tree_based_dsa_1;
pub mod tree_based_dsa_2;
fn main() {}
